name: Zeah testing!

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Download OrigamiWand artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build-on-tag.yaml
        name: OrigamiWand-build
        repo: Darxoon/OrigamiWand
    
    - name: Yes
      run: pwd
    - name: Yes2
      run: ll
        